[build]
  command = "npm run build"
  publish = "build"

# Duplicate headers (optional if using _headers). Netlify merges; keep here for clarity.
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    X-XSS-Protection = "0"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://accounts.google.com https://apis.google.com https://www.googletagmanager.com 'unsafe-inline'; connect-src 'self' https://accounts.google.com https://apis.google.com https://www.googleapis.com https://res.cloudinary.com https://api.brevo.com https://*.brevo.com https://*.mongodb.net https://capstone-sumbong.vercel.app/ https://*.render.com wss://*.render.com; img-src 'self' data: blob: https://res.cloudinary.com https://lh3.googleusercontent.com https://*.googleusercontent.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src https://accounts.google.com https://apis.google.com; media-src 'self' https://res.cloudinary.com; object-src 'none'; base-uri 'self'; form-action 'self' https://accounts.google.com; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content;"
